<?php
$_seachHelper = Mage::helper('enterprise_search');
?>
<table border="0" cellpadding="0" cellspacing="0">
    <tr>
        <td>
            <strong><?php echo $this->__('Use Solr'); ?>:</strong>
        </td>
        <td>
            <?php echo $_seachHelper->isThirdPartSearchEngine() ? $this->__('Yes') : $this->__('No'); ?>
        </td>
    </tr>

    <tr>
        <td>
            <strong><?php echo $this->__('Use in catalog'); ?>:</strong>
        </td>
        <td>
            <?php echo $_seachHelper->getSearchConfigData('solr_server_use_in_catalog_navigation') ? $this->__('Yes') : $this->__('No'); ?>
        </td>
    </tr>

    <tr>
        <td>
            <strong><?php echo $this->__('Is engine currently active'); ?>:</strong>
        </td>
        <td>
            <?php echo $_seachHelper->isActiveEngine() ? $this->__('Yes') : $this->__('No'); ?>
        </td>
    </tr>
</table>
