<?php
$_seachHelper = Mage::helper('enterprise_search');
?>
<table border="0" cellpadding="0" cellspacing="0">
    <tr>
        <td>
            <strong><?php echo $this->__('Solr Configured'); ?>:</strong>
        </td>
        <td>
            <?php echo $_seachHelper->isThirdPartSearchEngine() ? $this->__('Yes') : $this->__('No'); ?>
        </td>
    </tr>

    <tr>
        <td>
            <strong><?php echo $this->__('Configured to be used in navigation'); ?>:</strong>
        </td>
        <td>
            <?php echo $_seachHelper->getSearchConfigData('solr_server_use_in_catalog_navigation') ? $this->__('Yes') : $this->__('No'); ?>
        </td>
    </tr>

    <tr>
        <td>
            <strong><?php echo $this->__('Is engine used for Navigation'); ?>:</strong>
        </td>
        <td>
            <?php echo $_seachHelper->getIsEngineAvailableForNavigation(true) ? $this->__('Yes') : $this->__('No'); ?>
        </td>
    </tr>

    <tr>
        <td>
            <strong><?php echo $this->__('Is engine used for Search'); ?>:</strong>
        </td>
        <td>
            <?php echo $_seachHelper->getIsEngineAvailableForNavigation(false) ? $this->__('Yes') : $this->__('No'); ?>
        </td>
    </tr>
</table>
